feat: выполнено задание спринт 13
Krivinsky/java-shareit pull request #1
Opened 2022-12-04 20:47 UTC by Krivinsky

2022-12-07 18:37 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
>   * TODO Sprint add-controllers.
Осталось TODO, хотя контроллер уже добавлен.

2022-12-07 18:39 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDtoResponse update(@RequestBody UserDtoRequest userDtoRequest, @PathVariable Long userId) throws UserException, ValidationException {
Если попробовать сделать PUT, то возникает 500-я ошибка.
{
	"name": "Возникло исключение",
	"description": "Ошибка входных данных"
}

2022-12-07 22:37:44.821  INFO 25951 --- [nio-8080-exec-5] r.p.shareit.exeption.ErrorHandler        : 500 Request method 'PUT' not supported

org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'PUT' not supported

Все-таки это не ошибка на стороне сервера, а просто такого эндпоинта не существует. Похоже это должно быть 404

2022-12-07 18:40 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +    protected static Long generateId() {
функция называется так же, как и поле. Лучше, если названия будут разными

2022-12-07 18:50 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Всего несколько замечаний из разряда "можно лучше"

2022-12-08 14:35 UTC, avfyodorov reviewed
Добрый день, Евгений!

Замечания к прошлой версии исправлены. Новых замечаний нет.
 Работа принята.

2022-12-19 17:33 UTC, merged