Add bookings
Krivinsky/java-shareit pull request #2
Opened 2023-01-04 21:02 UTC by Krivinsky

2023-01-05 18:50 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.info("");
Пустые логи. Лучше добавить настоящее логирование, чтобы были видны входные и выходные параметры, результаты работы...

2023-01-05 18:57 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = itemService.creatItem(itemDto, userId);
Если отправить запрос на создание item на пользователя, которого нет, то в лог сообщение об ошибке  не выводится, клиент так же получается просто 404 {
	"timestamp": "2023-01-05T18:55:58.844+00:00",
	"status": 404,
	"error": "Not Found",
	"path": "/items"
}
Хотя было бы здорово получить сообщение об ошибки из эксепшена, что такого пользователя нет

2023-01-05 18:59 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto creat(@Valid @RequestBody UserDto userDto) {
create пишется c e на конце. Это небольшая грамматическая ошибка. Не только алгоритм должен быть чистым и красивым, но и сами слова в коде тоже. Т.к. код будут читать зарубежные коллеги.

2023-01-05 19:00 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User user = UserMapper.toUser(userDto);
При создании еще одного пользователя с такими же данными клиенту лучше получить сообщение об ошибке, которое говорит, что такой пользователь уже есть, сейчас приходит 500 и в логах ошибки
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["PUBLIC.UK_6DOTKOTT2KJSP8VW4D0M25FB7_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ 'email32@email.com' )"; SQL statement:
insert into users (id, email, name) values (default, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause

org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.UK_6DOTKOTT2KJSP8VW4D0M25FB7_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ 'email32@email.com' )"; SQL statement:
insert into users (id, email, name) values (default, ?, ?) [23505-214]

2023-01-05 19:01 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto update(@RequestBody UserDto userDto, @PathVariable Long userId) throws NotFoundException {
Если прислать неверный запрос, то падает и клиенту приходит 500, а на самом деле должен приходить Bad Request
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction] with root cause

javax.validation.ConstraintViolationException: Validation failed for classes [ru.practicum.shareit.user.User] during update time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='must be a well-formed email address', propertyPath=email, rootBeanClass=class ru.practicum.shareit.user.User, messageTemplate='{javax.validation.constraints.Email.message}'}

2023-01-05 19:20 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/exeption/ErrorHandler.java
> -@RestControllerAdvice
Почему advice был удален? Он ведь нужен вроде

2023-01-05 19:20 UTC, EvgenyKoptubenko requested changes
Есть несколько замечаний по обработке исключений

2023-01-07 12:08 UTC, Krivinsky commented on src/main/java/ru/practicum/shareit/exeption/ErrorHandler.java
> -@RestControllerAdvice
Переделал, поэтому удалил.

2023-01-07 12:25 UTC, Krivinsky commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto update(@RequestBody UserDto userDto, @PathVariable Long userId) throws NotFoundException {
В проверочных тестах ожидают 409 или 500.
pm.expect(pm.response.code).to.be.oneOf([409, 500]);

Добавил сообщение "Такой пользователь уже существует"

2023-01-07 17:37 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо

2023-01-09 07:21 UTC, merged